image: docker:19.03.12

stages:
  - build
  - docker-build
  - release
  - docker-build-release

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

# Rules that applies to PIPELINE creation (not individual jobs)
workflow:
  rules:
    # Avoid pipeline creation for maven release plugin commits
    - if: $CI_COMMIT_MESSAGE =~ /^\[maven\-release\-plugin\]/
      when: never
    # Else (other): Run always
    - when: always

.mvn_build_and_it_tests:
  services:
    - name: postgres:13.4
      alias: it-postgres
    - name: rabbitmq:3.9.5
      alias: it-rabbitmq
  variables:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://it-postgres:5432/it-database"
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: changeme
    SPRING_RABBITMQ_HOST: it-rabbitmq
    SPRING_RABBITMQ_PORT: 5672
    POSTGRES_DB: "it-database"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "changeme"
  artifacts:
    paths:
      - scheduler-service/target/*.jar
      - scheduler-service-models/target/*.jar
    expire_in: 1 week

# For merge requests do not `deploy` but only run `verify`.
maven-build-verify:
  image: maven:3.8.2-jdk-11
  extends: .mvn_build_and_it_tests
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify -s ci_settings.xml -P ci-it-test'
  except:
    - master

maven-build-deploy:
  image: maven:3.8.2-jdk-11
  extends: .mvn_build_and_it_tests
  stage: build
  script:
    - if [ ! -f ci_settings.xml ];
      then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml -P ci-it-test'
  only:
    - master

docker-build:
  stage: docker-build
  variables:
    # Do not clone. Not needed
    GIT_STRATEGY: none
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest ./scheduler-service
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

mvn-release:
  image: maven:3.8.2-jdk-11
  extends: .mvn_build_and_it_tests
  stage: release
  when: manual
  allow_failure: false
  before_script:
    - 'mkdir -p ~/.ssh/'
    - echo -n "$DEPLOY_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - 'cp $KNOWN_HOSTS ~/.ssh/known_hosts'
    - 'apt-get update && apt-get install -y git'
    - 'git config --global user.email "noreply@your.gitlab.host"'
    - 'git config --global user.name "GitLab CI"'
    - 'git checkout -B "$CI_COMMIT_REF_NAME"'
  script:
    - if [ ! -f ci_settings.xml ];
      then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions.";
      fi
    # Grab jar name and version and add it to the dotenv file for further docker usage
    - echo "BUILD_VERSION=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f scheduler-service/pom.xml | cut -d '-' -f1)" >> build.env
    - echo "SPRING_BOOT_JAR_FILE=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout -f scheduler-service/pom.xml)-$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f scheduler-service/pom.xml | cut -d '-' -f1).jar" >> build.env
    - 'mvn release:clean release:prepare release:perform -s ci_settings.xml -P ci-it-test'
  variables:
    # Ensure that the full repo is cloned on every execution. Fixes some issues about tags removed from remote but not in cache
    GIT_STRATEGY: clone
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - scheduler-service/target/*.jar
      - scheduler-service-models/target/*.jar
    expire_in: 1 week
  only:
    - master

docker-release-tag:
  stage: docker-build-release
  variables:
    # Need to gather the whole repo to obtain the Dockerfile
    GIT_STRATEGY: clone
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$BUILD_VERSION --build-arg JAR_FILE=./target/$SPRING_BOOT_JAR_FILE ./scheduler-service
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$BUILD_VERSION
  only:
    - master
